version: '3.4'

services:
  aggrid:
    image: aggrid
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3000"
    networks:
      - aggrid-network

  aggrid-nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/star_metricstream_com.crt:/etc/nginx/star_metricstream_com.crt:ro
      - ./ssl/star_metricstream_com.key:/etc/nginx/star_metricstream_com.key:ro
      - ./ssl/dhparam.pem:/etc/nginx/dhparam.pem:ro
    depends_on:
      - aggrid
    ports:
      - "8080:80"
      - "5443:443"  
    networks:
      - aggrid-network

networks:
  aggrid-network:
